<?php

namespace App\Domain\Application;

enum ApplicationStatus: string
{
    case DRAFT = 'DRAFT';
    case SUBMITTED = 'SUBMITTED';
    case PENDING_REVIEW = 'PENDING_REVIEW';
    case CLARIFICATION_REQUESTED = 'CLARIFICATION_REQUESTED';
    case CLARIFICATION_RECEIVED = 'CLARIFICATION_RECEIVED';
    case ADMISSIBLE = 'ADMISSIBLE';
    case INADMISSIBLE = 'INADMISSIBLE';
    case IN_EVALUATION = 'IN_EVALUATION';
    case EVALUATED = 'EVALUATED';
    case SHORTLISTED = 'SHORTLISTED';
    case NOT_SHORTLISTED = 'NOT_SHORTLISTED';
    case FINALIST = 'FINALIST';
    case SELECTED = 'SELECTED';
    case WAITLISTED = 'WAITLISTED';
    case NOT_SELECTED = 'NOT_SELECTED';
}
